### ISSUE TITLE
Doubts about the extension performance

### ISSUE THREAD

**Issue by webmasterchiclana** [jweiland-net/reserve#94]
Good morning, I have installed the reserve extension in typo3 9.5.23 and I do not understand how it works when scanning a qr code. On the ticket scan page I get a message: "Unable to access video stream (please make sure you have a camera enabled)" and I don't understand its meaning. Could you please explain to me how the process to scan the qr code works? Thanks.

**Comment by jweiland** [comment]
Scanning the QR code on the ticket is meant to be done with the camera of a mobile device (smartphone, tablet). Since the scanning is done via the browser, the browser needs access to the camera in the mobile device. You may need to enable camera access for the browser in the data protection settings of the mobile device.

**Comment by webmasterchiclana** [comment]
Thank you very much for the answer. I have the camera enabled for chrome on my mobile device but it keeps giving me the same message: Unable to access video stream (please make sure you have a camera enabled). I don't know what to do at this point.

One question: once the mobile recognizes the qr code, what happens? How is the redemption done?

**Comment by jweiland** [comment]
Your smartphone needs to have the ability to decode QR codes from images. The QR code contains an URL, which should then be opened in a browser. By opening the URL in the browser, the reservation is checked. 
We have tested this with iPhone as well as multiple Android phones. You may need to try this with a different phone, as not every phone may support this feature. 
Of course, you also need an active internet connection for the phone, since the URL points to the website with the reserve extension. Without an internet connection (WLAN or mobile provider) the verification by phone can not work.

**Comment by webmasterchiclana** [comment]
Perfect. I'm going to try another phone. Thank you very much for your reply.
